version: '3'
services:
  bootstrapper:
    image: "nembery/panos_bootstrapper:latest"
    ports:
    - "127.0.0.1:5001:5000"
    volumes:
     - ./content_updates:/var/tmp/content_updates/
  aframe:
    image: "nembery/aframe:latest"
    ports:
     - "8088:8000"
    volumes:
     - ./aframe/imports:/app/aframe/conf/imports
     - ./aframe/aframe.conf:/app/aframe/conf/aframe.conf
  content_downloader:
    image: "nembery/panos_content_downloader:latest"
    ports:
     - "5003:5003"
    volumes:
      - ./content_updates:/var/tmp/content_updates/
  welcome:
    image: alpine
    depends_on:
      - aframe
    command: sh -c 'chmod +x /tmp/w/wait-for.sh && /tmp/w/wait-for.sh aframe:8000 -- sleep 10 && cat /tmp/w/welcome.txt'
    volumes:
      - ./welcome:/tmp/w