version: '3'
services:
  bootstrapper:
    image: "paloaltonetworks/panos-bootstrapper:latest"
    ports:
    - "5000:5000"
    volumes:
     - ./content_updates:/var/tmp/content_updates/
  cnc:
    build: cnc
    ports:
      - 80:80
    volumes:
      - $HOME/.pan_cnc:/root/.pan_cnc
      - $HOME/.panrc:/root/.panrc
  content_downloader:
    image: "nembery/panos_content_downloader:latest"
    ports:
     - "5003:5003"
    volumes:
      - ./content_updates:/var/tmp/content_updates/
